version: '3.8'

services:
  monopoly-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    command: npm run dev 